spring:
  datasource:
    url: jdbc:h2:mem:sharxpenses;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
