spring:
  application:
    name: sharxpenses-backend

  datasource:
    url: jdbc:h2:mem:sharxpenses;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

# acesse Swagger em /swagger-ui/index.html
